-- ~/.config/nvim/init.lua

require('core.keymap')
require('core.options')
require('core.tabline')

require('languages.bash')
require('languages.cpp')
require('languages.java')
require('languages.lua')
require('languages.python')
require('languages.rust')
require('languages.sonar')

require('plugins.cmp')
require('plugins.cmp-lsp')
require('plugins.cmp-snip')
require('plugins.colorizer')
require('plugins.dap')
require('plugins.devicons')
require('plugins.gitsigns')
require('plugins.jdtls')
require('plugins.lazygit')
require('plugins.lspconfig')
require('plugins.luasnip')
require('plugins.mason')
require('plugins.neotree')
require('plugins.telescope')
