unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set number

set mouse-=a

set expandtab
set shiftwidth=4 smarttab

set clipboard=unnamedplus

xnoremap "+y y:call system("wl-copy", @")<cr>
nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p

call plug#begin('~/.config/vim/plugged')

Plug 'elkowar/yuck.vim'

call plug#end()
